datasets: #Provide below dataset name, schema configuration with restrictions to fields and size of schema
  user_info: #Dataset name
    schema:
      user_id: # Field 1
        type: IntegerType
        nullable: False
        restriction: 0:100
      user_name: # Field 2
        type: StringType
        nullable: False
        string_format: ?###???#?#?
        letters: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
      email: # Field 3 and etc
        type: StringType
        nullable: False
        values: jasongonzales@yahoo.com,patricia87@hotmail.com,mortega@hotmail.com,rachel24@hotmail.com,fmartin@yahoo.com,debbieperez@yahoo.com,dylanwilliams@yahoo.com,austin83@gmail.com,mark47@yahoo.com,daltonallen@hotmail.com,vsmith@gmail.com,kathryn82@hotmail.com,oliverrebecca@gmail.com,sdavis@hotmail.com,sandersjon@yahoo.com,gdaniels@gmail.com,blakewilliams@gmail.com,schmidtmisty@yahoo.com,edwin29@gmail.com,paulberry@hotmail.com,iray@gmail.com,zamorabrian@yahoo.com,wintersdaniel@hotmail.com,lisamartin@hotmail.com,hilladrian@gmail.com,erika45@hotmail.com,khansen@gmail.com,andrew77@yahoo.com,betty77@gmail.com,hulljordan@yahoo.com,chelsea28@hotmail.com,lesliecampbell@hotmail.com,stacy47@gmail.com,jenniferzamora@yahoo.com,alicialindsey@gmail.com,bakerallen@yahoo.com,heather75@hotmail.com,ascott@gmail.com,tgregory@yahoo.com,angelaadkins@gmail.com,steinrebecca@hotmail.com,donaldsonmarco@yahoo.com,alvarezpaula@hotmail.com,moranbradley@gmail.com,turnerdouglas@hotmail.com,zbaldwin@hotmail.com,fburns@yahoo.com,brian33@hotmail.com,fhill@hotmail.com,shansen@yahoo.com,desiree10@hotmail.com,jodihoward@yahoo.com,osborneteresa@hotmail.com,samuel59@yahoo.com,irodriguez@gmail.com,terri48@gmail.com,russellwilliam@gmail.com,valdezalexander@gmail.com,perezelijah@hotmail.com,hhumphrey@gmail.com,jonathanpark@hotmail.com,mauricethompson@yahoo.com,tcrawford@gmail.com,williamshaley@yahoo.com,tpineda@hotmail.com,jamesjackson@hotmail.com,jeffrey27@hotmail.com,zcosta@yahoo.com,lopezjasmin@yahoo.com,igomez@gmail.com,qgarcia@hotmail.com,francocatherine@hotmail.com,iking@yahoo.com,marybarber@gmail.com,xdavis@gmail.com,jeffrey84@gmail.com,ydavis@yahoo.com,davidrose@yahoo.com,brian25@gmail.com,pagemarcia@yahoo.com,nhill@gmail.com,krystalmoran@gmail.com,kmoody@yahoo.com,santosjohn@yahoo.com,scott16@hotmail.com,michealkey@hotmail.com,alisongordon@hotmail.com,mark93@hotmail.com,kathytanner@hotmail.com,george57@yahoo.com,mark36@gmail.com,jonathanmorris@gmail.com,cjones@hotmail.com,carriecabrera@gmail.com,wisemelanie@yahoo.com,jjennings@gmail.com,eric80@yahoo.com,zwhitehead@gmail.com,xallen@yahoo.com,kennethkelly@yahoo.com
      premium:
        type: BooleanType
        nullable: False
    size: 40
  user_buy:
    schema:
      user_id:
        type: IntegerType
        nullable: False
        #Restrictions:
      bought_date:
        type: DateType
        nullable: False
        restriction: 1200-01-01:2020-01-01
      product_id:
        type: IntegerType
        nullable: False
        #Restrictions:
    size: 20
  product:
    schema:
      product_id:
        type: IntegerType
        nullable: False
        #Restrictions:
      product_name:
        type: StringType
        nullable: False
        #Restrictions:
      price:
        type: DoubleType
        nullable: False
        #Restrictions:
    size: 20

#Unique restrictions should be passed as next sequence
#IntegerType Restrictions: min_value;max_value example:
#user_id: type:IntegerType restriction: 20000;300000




#Добавить флаг для повтора
restrictions:
  min_int: 0
  max_int: 100
  min_double: 0.0
  max_double: 100.0
  min_date: 1979-01-01
  max_date: 2047-12-02
  string_format: ?###???#?#?
  letters: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  save_to_csv: True # If true, result will be saved to csv format, else to Parquet

join_conditions:
  join_condition1:
    #left: user_info
    #right: user_buy
    condition: user_info.user_id = user_buy.user_id
    type: left
    intersecting_records: 20
  join_condition2:
    condition: user_buy.product_id = product.product_id
    type: right
    intersecting_records: 20